trigger:
  branches:
    include:
      - main  # Trigger the pipeline when changes are pushed to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Use the latest Ubuntu virtual machine for the build

variables:
  node_version: '16.x'  # Set the Node.js version (you can change this as required)
  build_dir: 'build'     # Build directory (React app's output folder)

jobs:
  - job: BuildAndDeploy
    displayName: 'Build and Deploy React Formik Library Management App'

    steps:
    # Step 1: Checkout the code from the repository
    - task: Checkout@1
      displayName: 'Checkout Code'

    # Step 2: Set up Node.js environment
    - task: UseNode@2
      inputs:
        versionSpec: $(node_version)
        addToPath: true
      displayName: 'Set up Node.js'

    # Step 3: Install dependencies
    - script: |
        npm install
      displayName: 'Install Dependencies'

    # Step 4: Run tests (Optional, if you have tests)
    # Uncomment the below lines if you have any tests
    # - script: |
    #     npm test -- --watchAll=false --ci --runInBand
    #   displayName: 'Run Tests'

    # Step 5: Build the React app
    - script: |
        npm run build
      displayName: 'Build React App'

    # Step 6: Deploy to Netlify (Adjust this for your hosting platform)
    - task: CmdLine@2
      inputs:
        script: |
          curl -sL https://github.com/netlify/cli/releases/download/v7.0.1/netlify-linux-x64.tar.gz | tar xz
          ./netlify deploy --dir=build --prod --auth YOUR_NETLIFY_AUTH_TOKEN --site YOUR_NETLIFY_SITE_ID
      displayName: 'Deploy to Netlify'
